#!/usr/bin/env bash
# Build each test app (app_sdk/<name>/app.c) into a .hb and regenerate the
# embedded copy the firmware uses. Requires the ESP-IDF env sourced.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
FW="$HERE/../../firmware_p4/components/Service"
MARCH=rv32imafc_zicsr_zifencei
MABI=ilp32f
# hb_pack needs PyNaCl, which lives in the system python, not the IDF venv.
PY="${SYSTEM_PYTHON:-/usr/bin/python3}"

for dir in "$HERE"/*/; do
  name="$(basename "$dir")"
  [ -f "$dir/app.c" ] || continue
  # ET_REL relocatable object: the split loader places code and writable data in
  # separate regions and patches every relocation, so no -fPIC / -shared.
  riscv32-esp-elf-gcc -march="$MARCH" -mabi="$MABI" \
    -Os -ffreestanding -fno-common -mno-relax -ffunction-sections -fdata-sections \
    -I"$FW/app_runtime/include" \
    -c -o "$dir/app.elf" "$dir/app.c"
  caps="$(cat "$dir/caps" 2>/dev/null || echo 0x20)" # per-app caps file, default UI
  "$PY" "$HERE/hb_pack.py" "$dir/app.elf" "$dir/app.hb" --name "$name" --caps "$caps" \
    --sign "$HERE/keys/dev_ed25519.key"
  OUT="$FW/app_runtime/include/${name}_hb.h"
  guard="$(echo "${name}_HB_H" | tr '[:lower:]' '[:upper:]')"
  {
    echo "// Generated by tools/app_sdk/build.sh. Embedded ${name}.hb for apprun."
    echo "#ifndef $guard"
    echo "#define $guard"
    echo "#include <stdint.h>"
    xxd -i -n "${name}_hb" "$dir/app.hb" | sed 's/unsigned char/static const uint8_t/; s/unsigned int/static const unsigned int/'
    echo "#endif // $guard"
  } > "$OUT"
  echo "built '$name' -> $OUT ($(stat -c%s "$dir/app.hb") bytes)"
done
