#!/usr/bin/env python3
# Generate a dev Ed25519 keypair. Writes the 32-byte private seed and emits the
# firmware trust-store header with the public key. DEV KEY: production uses a
# separately-managed key; the private key never ships in firmware.
import nacl.signing, sys, os

here = os.path.dirname(os.path.abspath(__file__))
fw = os.path.join(here, "..", "..", "firmware_p4", "components", "Service", "app_runtime", "include")
priv_path = os.path.join(here, "keys", "dev_ed25519.key")
hdr_path = os.path.join(fw, "tos_trust_keys.h")

sk = nacl.signing.SigningKey.generate()
open(priv_path, "wb").write(bytes(sk))          # 32-byte seed
pub = bytes(sk.verify_key)                        # 32-byte public key

def carr(b):
    return ", ".join(f"0x{x:02x}" for x in b)

with open(hdr_path, "w") as f:
    f.write("// Generated by tools/app_sdk/gen_key.py. Trusted app-signing public keys.\n")
    f.write("#ifndef TOS_TRUST_KEYS_H\n#define TOS_TRUST_KEYS_H\n#include <stdint.h>\n\n")
    f.write("#define TOS_TRUST_KEY_COUNT 1\n")
    f.write("static const uint8_t TOS_TRUST_KEYS[TOS_TRUST_KEY_COUNT][32] = {\n")
    f.write("    {" + carr(pub) + "},\n")
    f.write("};\n#endif // TOS_TRUST_KEYS_H\n")

print(f"wrote {priv_path} (private seed) and {hdr_path} (public key)")
